/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConductoresRouteImport } from './routes/conductores'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as ViajesRouteImport } from './routes/viajes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductoresRoute = ConductoresRouteImport.update({
  id: '/conductores',
  path: '/conductores',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesRoute = ViajesRouteImport.update({
  id: '/viajes',
  path: '/viajes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conductores': typeof ConductoresRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conductores': typeof ConductoresRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conductores': typeof ConductoresRoute
  '/vehiculos': typeof VehiculosRoute
  '/viajes': typeof ViajesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendario' | '/conductores' | '/vehiculos' | '/viajes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendario' | '/conductores' | '/vehiculos' | '/viajes'
  id:
    '__root__' | '/' | '/calendario' | '/conductores' | '/vehiculos' | '/viajes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConductoresRoute: typeof ConductoresRoute
  VehiculosRoute: typeof VehiculosRoute
  ViajesRoute: typeof ViajesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductores': {
      id: '/conductores'
      path: '/conductores'
      fullPath: '/conductores'
      preLoaderRoute: typeof ConductoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes': {
      id: '/viajes'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConductoresRoute: ConductoresRoute,
  VehiculosRoute: VehiculosRoute,
  ViajesRoute: ViajesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
